//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeService.srTruckService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srTruckService.ICANCodeInterface")]
    public interface ICANCodeInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICANCodeInterface/addDriverBehavior", ReplyAction="http://tempuri.org/ICANCodeInterface/addDriverBehaviorResponse")]
        void addDriverBehavior(string MACAddress, string behavior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICANCodeInterface/addDriverBehavior", ReplyAction="http://tempuri.org/ICANCodeInterface/addDriverBehaviorResponse")]
        System.Threading.Tasks.Task addDriverBehaviorAsync(string MACAddress, string behavior);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICANCodeInterfaceChannel : CodeService.srTruckService.ICANCodeInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CANCodeInterfaceClient : System.ServiceModel.ClientBase<CodeService.srTruckService.ICANCodeInterface>, CodeService.srTruckService.ICANCodeInterface {
        
        public CANCodeInterfaceClient() {
        }
        
        public CANCodeInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CANCodeInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CANCodeInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CANCodeInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addDriverBehavior(string MACAddress, string behavior) {
            base.Channel.addDriverBehavior(MACAddress, behavior);
        }
        
        public System.Threading.Tasks.Task addDriverBehaviorAsync(string MACAddress, string behavior) {
            return base.Channel.addDriverBehaviorAsync(MACAddress, behavior);
        }
    }
}
